{
  "formatVersion": "1.1",
  "component": {
    "group": "com.htc.vr",
    "module": "wvr_client",
    "version": "6.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "wvr_client-6.2.0.aar",
          "url": "wvr_client-6.2.0.aar",
          "size": 10270591,
          "sha512": "e2404d5a63ccbb19e8f0c3f47a6b3e1ea41bb0bf657328dc3885d87551188916c6b6c491bf82b143eb04b27e8cc2e68427dda47fa152af25bb366b526652b0c1",
          "sha256": "b14ced0d4c6d80e4ffff600100de3d5865aeea11095d884468381c81be04d796",
          "sha1": "44b21f94e03279376349a77d54c00df0c48eaffb",
          "md5": "e3ad71a79d75032cb7b32b930d974a57"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.htc.vr",
          "module": "vr.client.abi",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "wvr_client-6.2.0.aar",
          "url": "wvr_client-6.2.0.aar",
          "size": 10270591,
          "sha512": "e2404d5a63ccbb19e8f0c3f47a6b3e1ea41bb0bf657328dc3885d87551188916c6b6c491bf82b143eb04b27e8cc2e68427dda47fa152af25bb366b526652b0c1",
          "sha256": "b14ced0d4c6d80e4ffff600100de3d5865aeea11095d884468381c81be04d796",
          "sha1": "44b21f94e03279376349a77d54c00df0c48eaffb",
          "md5": "e3ad71a79d75032cb7b32b930d974a57"
        }
      ]
    }
  ]
}
